"""invoice counter series

Revision ID: 975c76440445
Revises: 70895b078bc0
Create Date: 2026-07-04 13:03:48.132098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975c76440445'
down_revision: Union[str, None] = '70895b078bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    invoice_series_enum = sa.Enum('gst', 'simple', name='invoice_series')
    invoice_series_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('invoice_counters', sa.Column('series', invoice_series_enum, nullable=False))
    op.alter_column('invoice_counters', 'fy_year',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_constraint('uq_invoice_counter_store_fy', 'invoice_counters', type_='unique')
    op.create_unique_constraint('uq_invoice_counter_store_series_fy', 'invoice_counters', ['store_id', 'series', 'fy_year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_invoice_counter_store_series_fy', 'invoice_counters', type_='unique')
    op.create_unique_constraint('uq_invoice_counter_store_fy', 'invoice_counters', ['store_id', 'fy_year'])
    op.alter_column('invoice_counters', 'fy_year',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('invoice_counters', 'series')
    sa.Enum(name='invoice_series').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
